# Page settings

baseURL = "/"
languageCode = "en"
title = "Marvin Schenkel"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Marvin Schenkel"
    description = "Marvin Schenkel CV"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Marvin Schenkel"
        tagline = ""
        avatar = "marvin.png"

    [params.contact]
        enable = true
        location = "Zeist, Utrecht"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+31(0)611090127"
        text = "+31(0)611090127"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"        
        url = "mailto: marvin@schenkel.dev"
        text = "marvin@schenkel.dev"

        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "//schenkel.dev"
        text = "www.schenkel.dev"
        
    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true 
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Computer Science (cum laude)"
        university = "HU University of Applied Sciences Utrecht"
        dates = "2009 - 2012"

        [[params.education.list]]
        degree = "Certificate of Excellence"
        university = "HU University of Applied Sciences Utrecht"
        dates = "2012"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Dutch"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Home Automation"
        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Home Barista"
        [[params.interests.list]]
        name = "Cooking"

    [params.summary]
        enable = true
        text = "I remember my first computer experience: sitting on my dad's lap as a 6-year-old and typing basic DOS-commands like `cd games` to start my favourite games. Now, 25-ish years later I am still using those commands to find my way while building data solutions. My passion is working on challenging data solutions in cloud environments, trying to apply software engineering best practices to everything I do. I have over 12 years of experience working on data (platform) engineering, data science and BI related projects for various clients in both Europe and Australia, such as Ahold Delhaize, Nationale-Nederlanden, Transavia, ASSA ABLOY and Jetstar Airways (AU)."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/MarvinSchenkel"
        title = "MarvinSchenkel"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/marvinschenkel"
        title = "marvinschenkel"