name: Deploy Hugo to Firebase
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: ryank90/action-hugo-firebase-deploy@master
      with:
        firebase-token: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHENKELDEV }}
        hugo-params: -D
      # - uses: actions/checkout@v2
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHENKELDEV }}'
      #     channelId: live
      #     projectId: schenkeldev